name: "Build Susu Jahe kernel"

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build Susujahe kernel"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout kernel source"
      uses: actions/checkout@v4
      with:
        repository: a02-trial/a022f_kernel

    - name: "Set variables"
      id: vars
      run: |
        echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -b 1-8 -)"
        echo "::set-output name=release_name::Susu-Jahe"

    - name: "Checkout zipper"
      uses: actions/checkout@v4
      with:
        repository: lemniskett/AnyKernel3
        path: zipper

    - name: "Android kernel build"
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: ${{ steps.vars.outputs.release_name }}
      with:
        arch: arm
        compiler: proton-clang/master/binutils
        defconfig: a02_defconfig
        image: Image.gz-dtb
